# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoSharing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoSharing

  pod 'SwiftLint'
  pod "SwiftFormat/CLI"

  # Amplify
  pod 'Amplify'

  # Auth
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'

  # DataStore
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'

  # Storage
  pod 'AmplifyPlugins/AWSS3StoragePlugin'

  # Kingfisher
  pod 'Kingfisher'
end
